

import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Top from "./components/widges/navigation/top";
import Footer from "./components/widges/footer";





const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "furniture website",
  description: "Generated by furniture website",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    
    <html lang="en">
      <body>
       <Top />
        {children}
        <Footer />
      </body>
    </html>
  
  );
}
